Fix CharacterGeoRenderer ClassCastException by adding createRenderState method
The renderer was attempting to cast LivingEntityRenderState to CharacterGeoRenderState,
causing a ClassCastException when characters were created. This was happening because
the renderer didn't override createRenderState() to specify the correct render state type.

Added the createRenderState() method to return a CharacterGeoRenderState instance,
ensuring the rendering system creates the correct state type for character entities.

Fixes the error:
java.lang.ClassCastException: class net.minecraft.client.render.entity.state.LivingEntityRenderState
cannot be cast to class ninja.trek.srd.client.render.geckolib.CharacterGeoRenderState